#!/bin/bash

manifest=components/components.manifest

rm -rf components/*.*

#echo "# Generated by xpcom_build.sh - Shoufu L." >> "$manifest"
#echo "" >> $manifest
#echo "" >> $manifest

for xpcom in xpcom_demo xpcom_osnapi xpcom_byzauth xpcom_chimera
do	
	if [ -d $xpcom ]; then
		echo "----> Building $xpcom <----"
		make clean -C $xpcom
		make -C $xpcom

		cat $xpcom/manifest >> "$manifest"
		echo " " >> "$manifest"
		rm -rf $xpcom/manifest $xpcom/*.xpt $xpcom/*.dSYM 
		rm -rf $xpcom/*.so $xpcom/*.dylib
	fi
done

