/**
 *  Copyright (c) 2012 Stevens Institute of Technology. 
 *  
 *  All rights reserved.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 *
 *	Author: Shoufu Luo
 * 	Mon Jan 2 6:36:10 EDT 2012 
 *
 */

#include "nsISupports.idl"

[scriptable, uuid(CAA85635-2700-4354-8E6D-95DD0D2AB433)]
interface iQueryCmmtCB:nsISupports
{
	void showCmmts();		
};

[scriptable, uuid(9361FFE4-BDBD-4C69-AC73-DA477B32CE43)]
interface iChimeraRider:nsISupports
{
	void	submitComment(in string url, in string author, in string content, 
							in long inherit, in long permission);

	void	queryCmmtsbyURL(in string url, in iQueryCmmtCB func);
	void	queryCmmtsbyURLAuthor(in string url, in string author, in iQueryCmmtCB func);
	void	queryCmmtsbyURLKeyword(in string url, in string keyword, in iQueryCmmtCB func);
};
